[Feat] 마일스톤 도메인 기능 개발
issue-tracker/issue-tracker-server pull request #41
Opened 2022-08-15 16:30 UTC by who-hoo

- [x] 마일스톤 도메인 설계
- [x] 마일스톤 조회 기능 구현
- [x] 마일스톤 전체 조회 기능 구현
- [x] 마일스톤 추가 기능 구현
- [x] 마일스톤 수정 기능 구현
- [x] 마일스톤 상태 수정 기능 구현
- [x] 마일스톤 삭제 기능 구현

---

마일스톤 전체 조회 시, 쿼리 파라미터로 `?isClosed=true|false` 필터를 적용할 수 있습니다. 
쿼리 파라미터 필터를 사용하지 않을 시에는 전체 마일스톤이 조회됩니다.

2022-08-15 16:30 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorMessage.java
> +    public static final String INVALID_DATE_FORMAT = "유효하지 않은 날짜 형식(YYYY-MM-DD)입니다.";
date format에 관한 에러는 공통적인 부분이라고 생각해서 common에 따로 작성했어요!

2022-08-15 16:31 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
> +		}
몬가 woowa한 방법은 없겠지요;;;

2022-08-15 16:33 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/AddMilestoneRequest.java
> +	@Pattern(regexp = "^\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])$", message = ErrorMessage.INVALID_DATE_FORMAT)
정규식을 뭔가 공통 상수로 빼고싶은데, `common` 패키지에 `util`같은거 만들까요?

2022-08-15 16:34 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestoneResponse.java
> +			(milestone.getDueDate() != null) ? milestone.getDueDate().format(DateTimeFormatter.ISO_LOCAL_DATE) : null,
이친구,,괜찮을까요,,

2022-08-15 17:33 UTC, ak2j38 requested changes
고생 많았어요!

몇 가지 궁금한 점이 있는데 요거는 토킹어바웃으로 하는걸로 하고!
피그마 25쪽에 보면 `열린 마일스톤/닫힌 마일스톤` 갯수 카운트되는 부분이 있는데 이 로직은 미구현된걸까요?

2022-08-15 17:33 UTC, ak2j38 commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestonesResponse.java
> +			.collect(Collectors.toList());
완벽한 불변성을 보장할 순 없겠지만 `unmodifiableList`을 사용하는 것은 어떨까요?

2022-08-15 17:33 UTC, ak2j38 commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/UpdateMilestoneRequest.java
> +	private String dueDate;
`String`인 이유가 따로 있을까요?

2022-08-15 17:33 UTC, ak2j38 commented on src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
> +		}
컨트롤러에서 `@RequestParam`을 이용해 `isClosed`를 받을 때 `defaultValue` 속성을 사용해보는 건 어떨까요?

2022-08-15 17:33 UTC, ak2j38 commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/AddMilestoneRequest.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
여기에는 `swagger 문서화`를 위한 어노테이션이 빠졌네요! (물론 저도...)

2022-08-15 17:33 UTC, ak2j38 commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/UpdateMilestoneRequest.java
> +public class UpdateMilestoneRequest {
여기에도 `swagger 문서화`를 위한 어노테이션이 빠졌네요!

2022-08-15 17:33 UTC, ak2j38 commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/AddMilestoneRequest.java
> +	@Pattern(regexp = "^\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])$", message = ErrorMessage.INVALID_DATE_FORMAT)
재사용되는 정규식이라면 `common`에 빼는 방법이 좋겠네요!

2022-08-15 17:33 UTC, ak2j38 commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestoneResponse.java
> +			(milestone.getDueDate() != null) ? milestone.getDueDate().format(DateTimeFormatter.ISO_LOCAL_DATE) : null,
특별히 해결할 방법이 안떠오르네요 😅

2022-08-15 17:38 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
> +		}
필터를 적용하고 싶지 않은 경우도 있어서요! findByIsClosed에 null도 먹나요?! 한번실험해보겠습니다.

2022-08-15 17:38 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/AddMilestoneRequest.java
> +	@Pattern(regexp = "^\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])$", message = ErrorMessage.INVALID_DATE_FORMAT)
추출 진행하겠습니다.

2022-08-15 17:38 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestoneResponse.java
> +			(milestone.getDueDate() != null) ? milestone.getDueDate().format(DateTimeFormatter.ISO_LOCAL_DATE) : null,
😢

2022-08-15 17:40 UTC, who-hoo commented
> 피그마 25쪽에 보면 열린 마일스톤/닫힌 마일스톤 갯수 카운트되는 부분이 있는데 이 로직은 미구현된걸까요?

깜빡스;; 요구사항 분석을 부실하게했네요ㅋㅋㅋㅋ있는 줄도 몰랐음;; 오늘도 레전드인 나;;

2022-08-16 05:32 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
> +		}
카운트 관련 요구사항도 반영해야 해서 응답 값으로 열린 마일스톤과 닫힌 마일스톤을 분리하여 반환하도록 수정하였습니다.

2022-08-16 05:33 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/AddMilestoneRequest.java
> +	@Pattern(regexp = "^\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])$", message = ErrorMessage.INVALID_DATE_FORMAT)
알려주신`String`이 아닌 `LocalDate`로 바로 받는 방법을 사용하면, 정규식 검증 로직이 아예 필요 없을 것 같아서 `LocalDate`로 타입 변경하고 추출 진행 취소하겠습다ㅋㅋ 👍

2022-08-16 05:36 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/MilestoneController.java
> +	@ResponseStatus(HttpStatus.OK)
쓰고싶어요... 통일감 좋아...

2022-08-16 05:36 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/MilestoneController.java
> +	@ResponseStatus(HttpStatus.OK)
제거 하갰읍니다. 😢

2022-08-16 05:39 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/MilestoneController.java
> +	}
맞습니다 지니어스 우진팍 👍

2022-08-16 05:40 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/UpdateMilestoneRequest.java
> +	private String dueDate;
`LocalDate`쓰면 바꿔주는지 몰랐기에,,데헷
yyyy-mm-dd 검증 빡세게 해야하는줄 알았읍니다 힛

2022-08-16 05:52 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/AddMilestoneRequest.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
추가 완료! 왓어꼼꼼맨 👍

2022-08-16 05:53 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/UpdateMilestoneRequest.java
> +public class UpdateMilestoneRequest {
추가 완료! 왓어꼼꼼맨22 👍

2022-08-16 05:55 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorMessage.java
> +    public static final String INVALID_DATE_FORMAT = "유효하지 않은 날짜 형식(YYYY-MM-DD)입니다.";
LocalDate로 요청값 타입 변경하면서, 필요 없어진 검증 로직이라서 삭제하였습니다!

2022-08-16 06:13 UTC, who-hoo commented on src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestonesResponse.java
> +			.collect(Collectors.toList());
`MilestonesResponse`에 누락된 접근 제어자 추가하였습니다! 이제 마일스톤스를 건드릴순 없을겁니다 하핫

2022-08-16 06:13 UTC, who-hoo commented
@ak2j38 재검토 해 주 세 요

2022-08-16 07:27 UTC, merged